name:                generics-mrsop-gdiff
version:             0.0.2
license:             BSD3
license-file:        LICENSE
synopsis:            Reimplementation of the `gdiff` algorithm for `generics-mrsop`
description:         Here we port the gdiff algorithm and library to work over the `generics-mrsop`, 
                     enabling code that relies on the later library to access the gdiff algorithm. 
                     Moreover, we also bring in the utilities for converting a `gdiff` patch into
                     a more structured version, facilitating merging. For some literature on the
                     topic check Arian's MSc thesis at <https://dspace.library.uu.nl/handle/1874/380853>
                     or our TyDe 2017 paper at <https://victorcmiraldo.github.io/data/tyde2017.pdf>.
author:              Arian van Putten and Victor Miraldo
maintainer:          Victor Miraldo <v.cacciarimiraldo@gmail.com>
category:            Generics
github:              VictorCMiraldo/generics-mrsop-gdiff

dependencies:
  - base >= 4.9 && < 5
  - generics-mrsop >= 2.2.0

library:
  source-dirs: src/
  ghc-options: -Wall
 
